import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from'node:fs';
import{plans,quote,renderPage,media}from'./app.mjs';
test('Three plans match the September tariff in cents',()=>{assert.deepEqual(plans.map(p=>[p.id,p.monthly,p.annual,p.integration]),[['go',16900,172380,150000],['pro',34900,355980,150000],['intelligence',47900,488580,0]]);for(const p of plans)assert.equal(p.annual,p.monthly*12*.85);});
test('First invoice separates one-off integration and never waives it on annual Go/Pro',()=>{assert.equal(quote('go','monthly').initial,166900);assert.equal(quote('go','annual').initial,322380);assert.equal(quote('pro','annual').initial,505980);assert.equal(quote('intelligence','annual').initial,488580);assert.equal(quote('intelligence','monthly').initial,47900);});
test('Invalid query values cannot inject plans or markup',()=>{assert.equal(quote('<script>','invalid').plan.id,'go');assert.equal(quote('go','monthly').annual,false);});
test('Every route has a single H1 and skip-link destination',()=>{for(const p of ['/','/transgest/','/transgest/precios/','/transgest/contratar/','/solicitar-demo/','/formacion/','/planner/']){const html=renderPage(p);assert.equal((html.match(/<h1\b/g)||[]).length,1);assert.ok(html.includes('id="main"'));assert.ok(html.includes('Sin pagos')||html.includes('Sin cargos')||html.includes('Sin cobros')||html.includes('Sin pagos ni altas reales'));}});
test('No real submission, payment calls, tracking or persistent personal data',()=>{const js=readFileSync(new URL('./app.mjs',import.meta.url),'utf8');assert.doesNotMatch(js,/\bfetch\s*\(|sendBeacon\s*\(|XMLHttpRequest|localStorage|sessionStorage|stripe\.com|paypal\.com|document\.cookie/);assert.match(js,/e\.preventDefault\(\)/);assert.match(js,/No se ha efectuado ningún pago/);});
test('Media has safe names, caption and no invented recordings',()=>{for(const m of Object.values(media)){assert.match(m.file,/^[a-z-]+\.avif$/);assert.equal(m.clip,null);}assert.match(renderPage('/transgest/'),/No es una grabación de vídeo/);assert.match(renderPage('/transgest/'),/ficticios/);});
test('Preview deployment refuses main and production, has noindex and forbids external network',()=>{const build=readFileSync(new URL('./build.mjs',import.meta.url),'utf8');assert.match(build,/VERCEL_ENV==='production'/);assert.match(build,/VERCEL_GIT_COMMIT_REF==='main'/);const cfg=JSON.parse(readFileSync(new URL('../vercel.json',import.meta.url)));assert.ok(cfg.headers[0].headers.some(h=>h.key==='X-Robots-Tag'&&h.value.includes('noindex')));assert.ok(cfg.headers[0].headers.some(h=>h.key==='Content-Security-Policy'&&h.value.includes("connect-src 'none'")));});
