import {plans,money,quote,screens,media} from './catalog.mjs';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let billing='monthly',tourTimer=null,lastFocus=null;
function openDialog(dialog){lastFocus=document.activeElement;$('#hero-video')?.pause();dialog.showModal();document.body.style.overflow='hidden';}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$$('dialog').forEach(d=>{d.addEventListener('close',()=>{document.body.style.overflow='';$$('video',d).forEach(v=>v.pause());lastFocus?.focus();});d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});});
$$('[data-demo]').forEach(b=>b.addEventListener('click',()=>openDialog($('#demo-dialog'))));
function showScreen(id){const s=screens.find(x=>x.id===id);if(!s)return;const config=media[id],body=$('#viewer-body');body.replaceChildren();$('#viewer-title').textContent=s.title;$('#viewer-kind').textContent=s.kind;$('#viewer-caption').textContent=s.caption+' Identidades y datos ilustrativos; no se muestran datos de clientes.';if(config.videoSrc){const video=document.createElement('video');video.src=config.videoSrc;video.poster=config.poster;video.controls=true;video.preload='none';video.playsInline=true;if(config.captionsSrc){const tr=document.createElement('track');tr.kind='captions';tr.srclang='es';tr.label='Español';tr.src=config.captionsSrc;tr.default=true;video.append(tr);}body.append(video);}else{const img=new Image();img.src=config.poster;img.alt=s.title+', vista con datos de demostración';body.append(img);}openDialog($('#viewer'));}
document.addEventListener('click',e=>{const b=e.target.closest('[data-screen]');if(b)showScreen(b.dataset.screen);});
function selectHero(id){const s=screens.find(s=>s.id===id);if(!s||!$('#hero-image'))return;const v=$('#hero-video');if(v){v.pause();v.hidden=!media[id].videoSrc;$('#hero-image-button').hidden=!!media[id].videoSrc;if(media[id].videoSrc){v.src=media[id].videoSrc;v.poster=media[id].poster;if(!reduced.matches&&!navigator.connection?.saveData&&!document.hidden)v.play().catch(()=>{});}}$('#hero-image').src=media[id].poster;$('#hero-image').alt=s.title+', datos ilustrativos';$('#hero-screen-title').textContent=s.title;$('#hero-image-button').dataset.screen=id;$('#hero-image-button').setAttribute('aria-label','Ampliar '+s.title);$('#hero-media-note').textContent=s.kind+'. Recorrido de capturas; no es una grabación de acciones.';$$('[data-hero]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.hero===id)));}
function stopTour(){clearInterval(tourTimer);tourTimer=null;const b=$('#tour-toggle');if(b){b.textContent='▷ Recorrido visual';b.setAttribute('aria-pressed','false');}}
$$('[data-hero]').forEach(b=>b.addEventListener('click',()=>{stopTour();selectHero(b.dataset.hero);}));
$('#tour-toggle')?.addEventListener('click',()=>{if(tourTimer){stopTour();return;}let index=Math.max(0,screens.findIndex(s=>s.id===$('#hero-image-button').dataset.screen));if(reduced.matches||navigator.connection?.saveData){selectHero(screens[(index+1)%5].id);return;}const b=$('#tour-toggle');b.textContent='Ⅱ Pausar recorrido';b.setAttribute('aria-pressed','true');tourTimer=setInterval(()=>{if(document.hidden||$('#viewer').open||$('#demo-dialog').open)return;index=(index+1)%5;selectHero(screens[index].id);},4800);});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTour();});reduced.addEventListener('change',()=>{stopTour();$('#hero-video')?.pause();});
if($('#hero-video')&&'IntersectionObserver' in window){new IntersectionObserver(entries=>{for(const e of entries)if(!e.isIntersecting)e.target.pause();},{threshold:.1}).observe($('#hero-video'));}
const steps=[['pedidos','Pedidos y tráfico','El servicio empieza con toda la información en su sitio.'],['mesa-nueva','Planificación','Ve la semana. Organiza lo que viene.'],['dashboard','Control operativo','Lo importante no debería perderse entre pantallas.'],['finanzas','Administración','La operación continúa en administración.']];
function selectStep(n,focus=false){if(!steps[n])return;const[id,label,title]=steps[n];$$('[data-step]').forEach((b,i)=>{b.setAttribute('aria-selected',String(n===i));b.tabIndex=n===i?0:-1;$('.step-plus',b).textContent=n===i?'−':'+';});$('#workflow-panel').setAttribute('aria-labelledby','step-'+n);$('#flow-label').textContent=label;$('#flow-title').textContent=title;const im=$('#flow-image-button img');im.src=media[id].poster;im.alt=screens.find(s=>s.id===id).title+', datos de demostración';$('#flow-image-button').dataset.screen=id;$('#flow-expand').dataset.screen=id;if(focus)$('#step-'+n).focus();}
$$('[data-step]').forEach(b=>{b.addEventListener('click',()=>selectStep(Number(b.dataset.step)));b.addEventListener('keydown',e=>{let i=Number(b.dataset.step),n=i;if(['ArrowDown','ArrowRight'].includes(e.key))n=(i+1)%4;else if(['ArrowUp','ArrowLeft'].includes(e.key))n=(i+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();selectStep(n,true);});});
function updatePricing(cycle){billing=cycle==='annual'?'annual':'monthly';$$('[data-billing]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.billing===billing)));$$('.plan[data-plan]').forEach(card=>{const p=plans.find(p=>p.id===card.dataset.plan);$('[data-price]',card).textContent=money(billing==='annual'?p.annual/12:p.monthly);$('[data-billing-caption]',card).textContent=billing==='annual'?`${money(p.annual)} al año · pago anual · sin IVA`:'Facturación mensual · sin IVA';$('[data-saving]',card).textContent=billing==='annual'?`Ahorras ${money(p.monthly*12-p.annual)} al año en la suscripción`:'';$('[data-buy]',card).href=`/transgest/contratar/?plan=${p.id}&billing=${billing}`;});}
$$('[data-billing]').forEach(b=>b.addEventListener('click',()=>updatePricing(b.dataset.billing)));
if($('#checkout-form')){
 const params=new URLSearchParams(location.search);const selected=plans.some(p=>p.id===params.get('plan'))?params.get('plan'):'go';$('#checkout-plan').value=selected;const initialBilling=params.get('billing')==='annual'?'annual':'monthly';$(`input[name=billing][value=${initialBilling}]`).checked=true;
 let currentStep=1;
 function currentQuote(){return quote($('#checkout-plan').value,$('input[name=billing]:checked').value,$('#ai-blocks').value,$('#storage-blocks').value);}
 function refresh(){const q=currentQuote();$('#ai-option').hidden=q.plan.id!=='intelligence';if(q.plan.id!=='intelligence')$('#ai-blocks').value='0';$('#summary-plan').textContent=`TransGest ${q.plan.name}`;$('#summary-cycle').textContent=q.cycle==='annual'?'Suscripción anual · 15 % de ahorro':'Suscripción mensual';$('#subscription-label').textContent=q.cycle==='annual'?'Suscripción · 12 meses':'Suscripción · primer mes';$('#summary-subscription').textContent=money(q.subscription);$('#summary-integration').textContent=q.integration?money(q.integration):'Incluida';$('#summary-extras').textContent=q.extrasMonthly?money(q.extrasMonthly):'Sin extras';$('#summary-initial').textContent=money(q.initial);$('#summary-renewal').textContent=q.cycle==='annual'?`Suscripción: ${money(q.subscription)}/año. ${q.extrasMonthly?`Extras: ${money(q.extrasMonthly)}/mes (el primer mes figura arriba).`:'Sin extras mensuales.'} La integración no se repite. Importes sin IVA.`:`Siguientes mensualidades: ${money(q.subscription+q.extrasMonthly)}/mes, sin IVA. La integración es un pago único.`;$('#summary-saving').textContent=q.cycle==='annual'?`Ahorro anual en suscripción: ${money(q.saving)}.`:'';$('#checkout-integration').textContent=q.integration?`Integración estándar: ${money(q.integration)} de pago único, también en modalidad anual. Se suma al importe inicial. Alcance de la integración a concretar.`:'Integración estándar incluida en Pro Intelligence. Nuevos conectores y servicios específicos se presupuestan aparte.';
 const final=$('#final-selection');final.replaceChildren();for(const[label,value]of[['Plan',`TransGest ${q.plan.name}`],['Periodicidad',q.cycle==='annual'?'Anual':'Mensual'],['Empresa','Empresa de demostración'],['Extras mensuales',money(q.extrasMonthly)],['Importe inicial sin IVA',money(q.initial)]]){const row=document.createElement('div');row.className='selection-row';const a=document.createElement('span'),b=document.createElement('strong');a.textContent=label;b.textContent=value;row.append(a,b);final.append(row);}}
 function goStep(n){if(![1,2,3].includes(n))return;currentStep=n;$$('[data-checkout-step]').forEach(s=>s.hidden=Number(s.dataset.checkoutStep)!==n);$$('[data-indicator]').forEach(s=>s.classList.toggle('active',Number(s.dataset.indicator)===n));refresh();const panel=$(`[data-checkout-step="${n}"]`);panel.setAttribute('tabindex','-1');panel.focus({preventScroll:true});if(innerWidth<720)panel.scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});}
 $$('[data-next]').forEach(b=>b.addEventListener('click',()=>goStep(Number(b.dataset.next))));$$('select,input[name=billing]',$('#checkout-form')).forEach(el=>el.addEventListener('change',refresh));$('#checkout-form').addEventListener('submit',e=>{e.preventDefault();if(currentStep!==3)return;$$('[data-checkout-step]').forEach(s=>s.hidden=true);const panel=$('#checkout-complete');panel.hidden=false;panel.tabIndex=-1;panel.focus();});refresh();
}
